### ISSUE TITLE
Pregunta Ferran

### ISSUE THREAD

**Issue by Ferrancf5** [bonastreyair/IIoT_CIM_UPC#21]
### **Primera pregunta**
Como puedo hacer una actualización del FORK que hice al principio?

### **Segunda pregunta**
No me deja hacer un pull request porqué ya hay uno? Es posible esto?

**Comment by bonastreyair** [comment]
@Ferrancf5 para la primera pregunta:
```
git fetch upstream
```

## Para la segunda pregunta

no es posible
